#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx6144M

#Gradle
org.gradle.jvmargs=-Xmx6144M -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.workers.max=2

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
